SELECT T.NAME as Name, T.sur_name as Surname,
CASE
	WHEN G.GENDER = 'M' THEN 'MUSKI'
	WHEN G.GENDER = 'F' THEN 'ZENSKI'
	ELSE 'OSTALO'
END AS GENDER,
C.name, C.average_income
FROM TRAINER T
JOIN GENDERS G ON T.GENDERID = G.ID
JOIN COUNTRY C ON T.COUNTRYID = C.ID
