INSERT INTO GENDERS (gender) VALUES
	('F'),
	('M')
SELECT * FROM GENDERS

INSERT INTO TRAINERTYPE (NAME) VALUES
	('Main'),
	('Helper')

INSERT INTO ACTIVITYTYPES (NAME) VALUES
	('Strength training'),
	('Cardio'),
	('Yoga'),
	('Dance'),
	('Injury Rehabilitation')

--INSERT INTO COUNTRY
--SELECT * FROM COUNTRY
--SELECT * FROM FITNESS_CENTER
--SELECT * FROM TRAINER
--SELECT * FROM MEMBER
--SELECT * FROM ACTIVITYTYPES
--SELECT * FROM ACTIVITY
--SELECT * FROm activity_helper_trainers
--SELECT * FROM ACTIVITY_INSTANCE
SELECT * FROM ACTIVITY_INSTANCE_MEMBER
SELECT * FROM TRAINERTYPE
SELECT * FROM GENDERS